'use client'

import React from 'react'
import { Config, Field } from '../types/catalog.types'
import ImageUploader from './ImageUploader'
import PackageSymptomsField from './PackageSymptomsField'
import PackageSchedulesField from './PackageSchedulesField'

const toSlug = (str: string) =>
  (str || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'd')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')

interface CatalogFormModalProps {
  modal: 'create' | 'edit' | null
  onClose: () => void
  onSubmit: (e: React.FormEvent) => void
  saving: boolean
  cfg: Config
  resource: string
  form: any
  setForm: React.Dispatch<React.SetStateAction<any>>
  options: Record<string, any[]>
  bookingMethodOptions: { code: string; name: string }[]
  fieldOptions: (source?: string) => any[]
  optionValue: (field: Field, option: any) => any
  generateCode: (resource: string) => string
  money: (val: unknown) => string
  readVietnameseCurrency: (val: unknown) => string
  symptomInput: string
  setSymptomInput: (val: string) => void
  aiSuggestedSymptoms: string[]
  setAiSuggestedSymptoms: React.Dispatch<React.SetStateAction<string[]>>
  loadingAiSymptoms: boolean
  onAiSuggest: () => void
  onAddSymptom: (text: string) => void
  onRemoveSymptom: (tag: string) => void
  onAddAllSuggested: () => void
}

export default function CatalogFormModal({
  modal,
  onClose,
  onSubmit,
  saving,
  cfg,
  resource,
  form,
  setForm,
  options,
  bookingMethodOptions,
  fieldOptions,
  optionValue,
  generateCode,
  money,
  readVietnameseCurrency,
  symptomInput,
  setSymptomInput,
  aiSuggestedSymptoms,
  setAiSuggestedSymptoms,
  loadingAiSymptoms,
  onAiSuggest,
  onAddSymptom,
  onRemoveSymptom,
  onAddAllSuggested,
}: CatalogFormModalProps) {
  if (!modal) return null

  return (
    <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-900/35 p-4 backdrop-blur-xs">
      <form onSubmit={onSubmit} className={`my-6 w-full ${resource === 'service-packages' ? 'max-w-4xl' : 'max-w-3xl'} rounded bg-white shadow-2xl border border-slate-200 overflow-hidden`}>
        <header className="flex items-center justify-between border-b border-slate-200 px-5 py-4 bg-slate-50/60">
          <strong className="text-slate-900 text-base">
            {modal === 'create' ? 'Thêm' : 'Cập nhật'} {cfg.singular}
          </strong>
          <button
            type="button"
            onClick={onClose}
            className="text-slate-400 hover:text-slate-700 text-xl leading-none px-1.5 py-0.5 rounded hover:bg-slate-100 transition cursor-pointer"
          >
            ×
          </button>
        </header>

        <div className="grid gap-4 p-5 sm:grid-cols-2 max-h-[75vh] overflow-y-auto">
          {resource === 'specialties' ? (
            <>
              {/* CỘT TRÁI: TÊN CHUYÊN KHOA + NÚT TẢI ICON INLINE */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Tên chuyên khoa <span className="text-[11px] font-normal text-slate-400">(Icon 1:1, SVG/PNG)</span>
                </label>
                <div className="flex items-center gap-2">
                  <ImageUploader
                    label=""
                    value={form.iconUrl || ''}
                    onChange={(url) => setForm({ ...form, iconUrl: url })}
                    aspectRatio="icon"
                  />
                  <input
                    type="text"
                    value={form.name ?? ''}
                    placeholder="Nhập tên chuyên khoa..."
                    onChange={(e) => {
                      const val = e.target.value
                      const updates: any = { name: val }
                      if (form.slugAutoGenerated !== false || !form.slug) {
                        updates.slug = toSlug(val)
                      }
                      setForm({ ...form, ...updates })
                    }}
                    className="flex-1 px-3 py-1.5 text-xs rounded border border-slate-200 bg-white transition-colors focus:outline-none focus:border-emerald-600 hover:border-slate-300"
                  />
                </div>
              </div>

              {/* CỘT PHẢI: SLUG SEO */}
              <div>
                <span className="block text-xs font-semibold text-slate-700 mb-1">Slug SEO</span>
                <input
                  type="text"
                  value={form.slug ?? ''}
                  placeholder="vd: tai-mui-hong"
                  onChange={(e) => {
                    setForm({
                      ...form,
                      slug: e.target.value.toLowerCase().replace(/\s+/g, '-'),
                      slugAutoGenerated: false,
                    })
                  }}
                  className="w-full px-3 py-1.5 text-xs font-mono rounded border border-slate-200 bg-white transition-colors focus:outline-none focus:border-emerald-600 hover:border-slate-300"
                />
              </div>

              {/* HÀNG RIÊNG: TRẠNG THÁI HOẠT ĐỘNG */}
              <div className="sm:col-span-2 flex items-center justify-between py-1 border-y border-slate-100">
                <span className="text-xs font-bold text-slate-700">Trạng thái hoạt động</span>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    role="switch"
                    aria-checked={form.isActive !== false}
                    onClick={() => setForm({ ...form, isActive: form.isActive === false })}
                    className={`relative inline-flex h-5 w-9 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none ${
                      form.isActive !== false ? 'bg-emerald-600' : 'bg-slate-300'
                    }`}
                  >
                    <span
                      className={`pointer-events-none inline-block h-4 w-4 transform rounded-full bg-white shadow-xs ring-0 transition duration-200 ease-in-out ${
                        form.isActive !== false ? 'translate-x-4' : 'translate-x-0'
                      }`}
                    />
                  </button>
                  <span className={`text-xs font-semibold ${form.isActive !== false ? 'text-emerald-700' : 'text-slate-500'}`}>
                    {form.isActive !== false ? 'Đang hoạt động' : 'Tạm ẩn'}
                  </span>
                </div>
              </div>

              {/* CƠ SỞ Y TẾ ÁP DỤNG */}
              <div className="sm:col-span-2">
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-xs font-bold text-slate-700">Cơ sở y tế áp dụng</span>
                  <label className="flex items-center gap-1.5 cursor-pointer select-none text-xs font-semibold text-emerald-800 hover:text-emerald-950">
                    <input
                      type="checkbox"
                      checked={Boolean(form.applyAllBranches)}
                      onChange={(e) => {
                        const checked = e.target.checked
                        setForm({
                          ...form,
                          applyAllBranches: checked,
                          branchIds: checked ? (options.branches || []).map((b: any) => b.id) : [],
                        })
                      }}
                      className="rounded accent-emerald-700"
                    />
                    Áp dụng cho tất cả cơ sở
                  </label>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5 rounded border border-slate-200 bg-white p-2">
                  {(options.branches || []).map((branch: any) => {
                    const isChecked = form.applyAllBranches || (form.branchIds || []).includes(branch.id)
                    return (
                      <label
                        key={branch.id}
                        className={`flex items-center gap-2 p-2 rounded text-xs transition cursor-pointer ${
                          isChecked ? 'bg-emerald-50/70 text-emerald-950 font-medium' : 'text-slate-600 hover:bg-slate-50'
                        }`}
                      >
                        <input
                          type="checkbox"
                          checked={isChecked}
                          disabled={Boolean(form.applyAllBranches)}
                          onChange={() => {
                            const current = form.branchIds || []
                            const next = current.includes(branch.id)
                              ? current.filter((id: string) => id !== branch.id)
                              : [...current, branch.id]
                            setForm({ ...form, branchIds: next })
                          }}
                          className="rounded accent-emerald-700"
                        />
                        <span className="truncate">{branch.name}</span>
                      </label>
                    )
                  })}
                </div>
              </div>

              {/* MÔ TẢ & TRIỆU CHỨNG */}
              <div className="sm:col-span-2">
                <label className="text-xs font-semibold text-slate-700 block mb-1">
                  Mô tả
                </label>
                <div className="space-y-3">
                  <textarea
                    rows={3}
                    value={form.description || ''}
                    onChange={(e) => setForm({ ...form, description: e.target.value })}
                    placeholder="Nhập nội dung mô tả, quyền lợi và hướng dẫn chuẩn bị..."
                    className="w-full rounded border border-slate-200 bg-white px-3 py-2 text-xs font-normal text-slate-800 hover:border-slate-300 focus:border-emerald-600 focus:outline-none transition-colors"
                  />
                  <PackageSymptomsField
                    form={form}
                    setForm={setForm}
                    symptomInput={symptomInput}
                    setSymptomInput={setSymptomInput}
                    aiSuggestedSymptoms={aiSuggestedSymptoms}
                    setAiSuggestedSymptoms={setAiSuggestedSymptoms}
                    loadingAiSymptoms={loadingAiSymptoms}
                    onAiSuggest={onAiSuggest}
                    onAddSymptom={onAddSymptom}
                    onRemoveSymptom={onRemoveSymptom}
                    onAddAllSuggested={onAddAllSuggested}
                  />
                </div>
              </div>
            </>
          ) : (
            cfg.fields.map((field) => {
              const [key, label, type, source] = field
              const wide = type === 'textarea' || type === 'multiselect'

              // Tên chi nhánh tích hợp nút tải ảnh/logo cơ sở inline
              if (resource === 'branches' && key === 'name') {
                return (
                  <div key={key} className="flex flex-col sm:col-span-2">
                    <label className="block text-xs font-semibold text-slate-700 mb-1">
                      Tên chi nhánh <span className="text-[11px] font-normal text-slate-400">(Ảnh/Logo)</span>
                    </label>
                    <div className="flex items-center gap-2">
                      <ImageUploader
                        label=""
                        value={form.imageUrl || ''}
                        onChange={(url) => setForm({ ...form, imageUrl: url })}
                        aspectRatio="icon"
                      />
                      <input
                        type="text"
                        value={form.name ?? ''}
                        placeholder="Nhập tên chi nhánh..."
                        onChange={(e) => setForm({ ...form, name: e.target.value })}
                        className="flex-1 px-3 py-1.5 text-xs rounded border border-slate-200 bg-white transition-colors focus:outline-none focus:border-emerald-600 hover:border-slate-300"
                      />
                    </div>
                  </div>
                )
              }
              if (resource === 'branches' && key === 'imageUrl') {
                return null
              }

              // Tên gói dịch vụ tích hợp nút tải ảnh minh họa inline
              if (resource === 'service-packages' && key === 'name') {
                return (
                  <div key={key} className="flex flex-col sm:col-span-2">
                    <label className="block text-xs font-semibold text-slate-700 mb-1">
                      Tên gói dịch vụ <span className="text-[11px] font-normal text-slate-400">(Ảnh minh họa)</span>
                    </label>
                    <div className="flex items-center gap-2">
                      <ImageUploader
                        label=""
                        value={form.imageUrl || ''}
                        onChange={(url) => setForm({ ...form, imageUrl: url })}
                        aspectRatio="icon"
                      />
                      <input
                        type="text"
                        value={form.name ?? ''}
                        placeholder="Nhập tên gói khám..."
                        onChange={(e) => {
                          const val = e.target.value
                          const updates: any = { name: val }
                          if (form.slugAutoGenerated !== false || !form.slug) {
                            updates.slug = toSlug(val)
                          }
                          setForm({ ...form, ...updates })
                        }}
                        className="flex-1 px-3 py-1.5 text-xs rounded border border-slate-200 bg-white transition-colors focus:outline-none focus:border-emerald-600 hover:border-slate-300"
                      />
                    </div>
                  </div>
                )
              }
              if (resource === 'service-packages' && key === 'imageUrl') {
                return null
              }

              // Giao diện chọn nhiều cơ sở khi tạo mới hoặc cập nhật gói khám
              if (resource === 'service-packages' && key === 'branchId') {
                const branchList = options.branches || []
                return (
                  <div key={key} className="sm:col-span-2 rounded border border-slate-200 bg-slate-50/40 p-3.5">
                    <div className="flex items-center justify-between mb-2">
                      <div>
                        <span className="block text-xs font-semibold text-slate-700">Cơ sở y tế áp dụng</span>
                        <span className="ml-2 text-[11px] text-slate-400 font-normal">
                          ({form.applyAllBranches ? 'Tất cả cơ sở' : `${form.branchIds?.length || 0}/${branchList.length} cơ sở đã chọn`})
                        </span>
                      </div>
                      <label className="flex items-center gap-1.5 cursor-pointer select-none text-xs font-semibold text-emerald-800 hover:text-emerald-950">
                        <input
                          type="checkbox"
                          checked={Boolean(form.applyAllBranches)}
                          onChange={(e) => {
                            const checked = e.target.checked
                            setForm({
                              ...form,
                              applyAllBranches: checked,
                              branchIds: checked ? branchList.map((b: any) => b.id) : [],
                            })
                          }}
                          className="rounded accent-emerald-700"
                        />
                        Áp dụng cho tất cả cơ sở
                      </label>
                    </div>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5 rounded border border-slate-200 bg-white p-2">
                      {branchList.map((branch: any) => {
                        const isChecked = form.applyAllBranches || (form.branchIds || []).includes(branch.id)
                        return (
                          <label
                            key={branch.id}
                            className={`flex items-center gap-2 p-2 rounded text-xs transition cursor-pointer ${
                              isChecked ? 'bg-emerald-50/70 text-emerald-950 font-medium' : 'text-slate-600 hover:bg-slate-50'
                            }`}
                          >
                            <input
                              type="checkbox"
                              checked={isChecked}
                              disabled={Boolean(form.applyAllBranches)}
                              onChange={() => {
                                const current = form.branchIds || []
                                const next = current.includes(branch.id)
                                  ? current.filter((id: string) => id !== branch.id)
                                  : [...current, branch.id]
                                setForm({ ...form, branchIds: next })
                              }}
                              className="rounded accent-emerald-700"
                            />
                            <span className="truncate">{branch.name}</span>
                          </label>
                        )
                      })}
                    </div>
                  </div>
                )
              }

              // Giao diện chọn nhiều hình thức đặt khám khi tạo mới hoặc cập nhật gói khám
              if (resource === 'service-packages' && key === 'branchBookingMethodId') {
                return (
                  <div key={key} className="sm:col-span-2">
                    <div className="flex items-center justify-between mb-1">
                      <span className="block text-xs font-semibold text-slate-700">Hình thức đặt khám áp dụng</span>
                      <span className="text-[11px] text-slate-400 font-normal">Có thể chọn nhiều hình thức</span>
                    </div>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-1 rounded border border-slate-200 bg-white p-2 hover:border-slate-300 transition-colors">
                      {bookingMethodOptions.map((method) => {
                        const isChecked = (form.bookingMethodCodes || []).includes(method.code)
                        return (
                          <label
                            key={method.code}
                            className="flex items-center gap-2 p-2 rounded text-xs font-normal hover:bg-slate-50 cursor-pointer"
                          >
                            <input
                              type="checkbox"
                              checked={isChecked}
                              onChange={() => {
                                const current = form.bookingMethodCodes || []
                                const next = current.includes(method.code)
                                  ? current.filter((c: string) => c !== method.code)
                                  : [...current, method.code]
                                setForm({ ...form, bookingMethodCodes: next })
                              }}
                            />
                            <span className={isChecked ? 'font-medium text-slate-900' : 'text-slate-600'}>
                              {method.name}
                            </span>
                          </label>
                        )
                      })}
                    </div>
                  </div>
                )
              }

              return (
                <div key={key} className={`flex flex-col ${wide ? 'sm:col-span-2' : ''}`}>
                  <label className="block text-xs font-semibold text-slate-700 mb-1">
                    {label}
                  </label>
                  {type === 'textarea' ? (
                    <div className="space-y-3">
                      <textarea
                        rows={3}
                        value={form[key] || ''}
                        onChange={(e) => setForm({ ...form, [key]: e.target.value })}
                        placeholder="Nhập nội dung mô tả, quyền lợi và hướng dẫn chuẩn bị..."
                        className="w-full px-3 py-2 text-xs rounded border border-slate-200 bg-white transition-colors focus:outline-none focus:border-emerald-600 hover:border-slate-300"
                      />

                      {/* COMPONENT TAGS TRIỆU CHỨNG LÂM SÀNG CHO GÓI KHÁM & CHUYÊN KHOA */}
                      {['service-packages', 'specialties'].includes(resource) && key === 'description' && (
                        <PackageSymptomsField
                          form={form}
                          setForm={setForm}
                          symptomInput={symptomInput}
                          setSymptomInput={setSymptomInput}
                          aiSuggestedSymptoms={aiSuggestedSymptoms}
                          setAiSuggestedSymptoms={setAiSuggestedSymptoms}
                          loadingAiSymptoms={loadingAiSymptoms}
                          onAiSuggest={onAiSuggest}
                          onAddSymptom={onAddSymptom}
                          onRemoveSymptom={onRemoveSymptom}
                          onAddAllSuggested={onAddAllSuggested}
                        />
                      )}
                    </div>
                  ) : type === 'select' ? (
                    <select
                      value={form[key] ?? ''}
                      onChange={(e) =>
                        setForm({
                          ...form,
                          [key]: source === 'specialties' ? Number(e.target.value) : e.target.value,
                          ...(key === 'branchId' ? { branchBookingMethodId: '' } : {}),
                        })
                      }
                      className="w-full px-2.5 py-1.5 text-xs rounded border border-slate-200 bg-white transition-colors focus:outline-none focus:border-emerald-600 hover:border-slate-300 cursor-pointer"
                    >
                      <option value="">Chọn {label.toLowerCase()}</option>
                      {fieldOptions(source).map((option) => (
                        <option key={option.id} value={optionValue(field, option)}>
                          {source === 'booking-methods' ? option.displayName : option.name}
                        </option>
                      ))}
                    </select>
                  ) : type === 'image' ? (
                    <div>
                      <ImageUploader
                        label=""
                        value={form[key] || ''}
                        onChange={(url) => setForm({ ...form, [key]: url })}
                        aspectRatio={key === 'iconUrl' ? 'square' : 'wide'}
                      />
                    </div>
                  ) : type === 'multiselect' ? (
                    <div className="grid max-h-48 gap-1 overflow-y-auto rounded border border-slate-200 bg-white p-2 sm:grid-cols-2 hover:border-slate-300 transition-colors">
                      {fieldOptions(source).map((option) => {
                        const checked = (form[key] || []).includes(String(option.id))
                        return (
                          <label key={option.id} className="flex items-center gap-2 rounded p-2 text-xs font-normal hover:bg-slate-50 cursor-pointer">
                            <input
                              type="checkbox"
                              checked={checked}
                              onChange={() =>
                                setForm({
                                  ...form,
                                  [key]: checked
                                    ? form[key].filter((id: string) => id !== String(option.id))
                                    : [...(form[key] || []), String(option.id)],
                                })
                              }
                            />
                            {option.name}
                          </label>
                        )
                      })}
                    </div>
                  ) : key === 'code' ? (
                    <div className="flex gap-2">
                      <input
                        type="text"
                        value={form[key] ?? ''}
                        onChange={(e) => setForm({ ...form, [key]: e.target.value })}
                        placeholder="Mã tự động..."
                        className="flex-1 px-3 py-1.5 text-xs font-normal uppercase rounded border border-slate-200 bg-white transition-colors focus:outline-none focus:border-emerald-600 hover:border-slate-300"
                      />
                      <button
                        type="button"
                        onClick={() => setForm({ ...form, code: generateCode(resource) })}
                        className="px-3 py-1.5 text-xs font-bold whitespace-nowrap rounded border border-slate-200 bg-slate-50 text-slate-700 hover:bg-slate-100 cursor-pointer flex items-center justify-center gap-1.5"
                        title="Tự động tạo mã mới"
                      >
                        <span className="text-amber-500">⚡</span> Tạo mã
                      </button>
                    </div>
                  ) : (
                    <input
                      type={type}
                      value={form[key] === 0 && modal === 'create' ? '' : (form[key] ?? '')}
                      placeholder={type === 'number' ? '0' : ''}
                      onFocus={(e) => {
                        if (type === 'number') {
                          e.target.select()
                        }
                      }}
                      onChange={(e) => {
                        if (type === 'number') {
                          const raw = e.target.value
                          if (raw === '') {
                            setForm({ ...form, [key]: '' })
                          } else {
                            const cleaned = raw.replace(/^0+(?=\d)/, '')
                            setForm({ ...form, [key]: cleaned === '' ? 0 : Number(cleaned) })
                          }
                        } else {
                          const val = e.target.value
                          const updates: any = { [key]: val }
                          if (key === 'name' && ['specialties', 'services', 'service-packages'].includes(resource) && (form.slugAutoGenerated !== false || !form.slug)) {
                            updates.slug = toSlug(val)
                          }
                          setForm({ ...form, ...updates })
                        }
                      }}
                      className="w-full px-3 py-1.5 text-xs rounded border border-slate-200 bg-white transition-colors focus:outline-none focus:border-emerald-600 hover:border-slate-300"
                    />
                  )}
                  {['price', 'unitPrice'].includes(key) && Number(form[key]) > 0 && (
                    <p className="mt-1 text-[11px] font-medium text-emerald-700 leading-normal">
                      <span className="font-semibold">{money(form[key])}</span>
                      {readVietnameseCurrency(form[key]) && (
                        <span className="text-slate-500 font-normal"> — {readVietnameseCurrency(form[key])}</span>
                      )}
                    </p>
                  )}
                </div>
              )
            })
          )}

          {resource === 'rooms' && (
            <label className="flex items-center gap-2 text-sm font-normal text-slate-700 sm:col-span-2 cursor-pointer">
              <input
                type="checkbox"
                checked={form.isActive !== false}
                onChange={(e) => setForm({ ...form, isActive: e.target.checked })}
              />
              Đang sử dụng
            </label>
          )}

          {resource === 'service-packages' && (
            <PackageSchedulesField form={form} setForm={setForm} />
          )}
        </div>

        <footer className="flex justify-end gap-2 border-t border-slate-200 px-5 py-4 bg-slate-50/60">
          <button
            type="button"
            onClick={onClose}
            className="rounded border border-slate-200 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100 cursor-pointer"
          >
            Hủy
          </button>
          <button
            disabled={saving}
            className="rounded bg-emerald-700 px-4 py-2 text-sm font-bold text-white hover:bg-emerald-800 disabled:opacity-50 cursor-pointer"
          >
            {saving ? 'Đang lưu…' : 'Lưu dữ liệu'}
          </button>
        </footer>
      </form>
    </div>
  )
}
