export { default as DoctorHome } from './pages/DoctorHome'
export { default as DoctorPrescriptionsPage } from './pages/DoctorPrescriptionsPage'
export { default as DoctorWorkSchedulesPage } from './pages/DoctorWorkSchedulesPage'
export { default as ClinicalQueuePage } from './pages/ClinicalQueuePage'
export { default as DoctorAppHeader } from './components/DoctorAppHeader'
export { default as IcdDiagnosisField } from './components/IcdDiagnosisField'
export * from './services/doctorService'
