'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { createUser, deleteUser, listUsers, updateUser } from '../services/users'

const ROLES = [
  ['all','Tất cả'],['doctor','Bác sĩ'],['pharmacist','Dược sĩ'],['receptionist','Lễ tân'],['branch_manager','Quản lý chi nhánh'],['cashier','Kế toán / Thu ngân'],
]
const ROLE_LABEL = Object.fromEntries(ROLES)
const EMPTY = { fullName:'', email:'', password:'', role:'doctor', isBlocked:false }

export default function ClinicStaffPage() {
  const [rows,setRows]=useState<any[]>([]), [filter,setFilter]=useState('all'), [query,setQuery]=useState(''), [loading,setLoading]=useState(true), [error,setError]=useState('')
  const [modal,setModal]=useState<'create'|'edit'|null>(null), [selected,setSelected]=useState<any>(null), [form,setForm]=useState<any>(EMPTY), [saving,setSaving]=useState(false)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await listUsers();setRows(result.data.filter((u:any)=>ROLES.some(([id])=>id===String(u.role||u.userType).toLowerCase())))}catch(e:any){setError(e?.response?.data?.message||e?.message||'Không tải được nhân sự.')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  const filtered=useMemo(()=>rows.filter((row)=>{const r=String(row.role||row.userType).toLowerCase();const q=query.trim().toLowerCase();return(filter==='all'||r===filter)&&(!q||`${row.fullName||''} ${row.email||''}`.toLowerCase().includes(q))}),[rows,filter,query])
  const openCreate=()=>{setSelected(null);setForm({...EMPTY,role:filter==='all'?'doctor':filter});setError('');setModal('create')}
  const openEdit=(row:any)=>{setSelected(row);setForm({fullName:row.fullName||'',email:row.email||'',password:'',role:String(row.role||row.userType).toLowerCase(),isBlocked:Boolean(row.isBlocked)});setError('');setModal('edit')}
  async function submit(e:React.FormEvent){e.preventDefault();if(!form.fullName.trim()||!form.email.trim())return setError('Vui lòng nhập họ tên và email.');if(modal==='create'&&form.password.length<6)return setError('Mật khẩu phải có ít nhất 6 ký tự.');setSaving(true);setError('');try{const payload={fullName:form.fullName.trim(),email:form.email.trim(),role:form.role,isBlocked:form.isBlocked,...(form.password?{password:form.password}:{})};if(modal==='create')await createUser({...payload,status:'active'});else await updateUser(selected.id,payload);setModal(null);await load()}catch(err:any){setError(err?.response?.data?.message||err?.message||'Không lưu được nhân sự.')}finally{setSaving(false)}}
  async function remove(row:any){if(!confirm(`Xóa tài khoản ${row.fullName||row.email}?`))return;try{await deleteUser(row.id);await load()}catch(e:any){setError(e?.response?.data?.message||e?.message||'Không xóa được tài khoản.')}}
  async function toggle(row:any){try{await updateUser(row.id,{isBlocked:!row.isBlocked});await load()}catch(e:any){setError(e?.response?.data?.message||e?.message||'Không cập nhật được trạng thái.')}}
  return <>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.13em] text-emerald-700">Quản lý người dùng</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Nhân sự phòng khám</h1><p className="mt-1 text-sm text-slate-500">Quản lý tài khoản và lọc nhân sự theo từng vai trò.</p></div><button onClick={openCreate} className="rounded-md bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white">+ Thêm nhân sự</button></div>
    {error&&<div className="mt-4 rounded-md border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
    <section className="mt-5 rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-100 p-4"><div className="flex flex-wrap gap-1.5">{ROLES.map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className={`rounded-md px-3 py-2 text-xs font-bold ${filter===id?'bg-emerald-700 text-white':'bg-slate-50 text-slate-500 hover:text-slate-800'}`}>{label}<span className="ml-1.5 opacity-70">{id==='all'?rows.length:rows.filter((r)=>String(r.role||r.userType).toLowerCase()===id).length}</span></button>)}</div><div className="mt-3 flex gap-2"><input value={query} onChange={(e)=>setQuery(e.target.value)} className="w-full max-w-md rounded-md border border-slate-200 px-3 py-2 text-sm outline-none focus:border-emerald-600" placeholder="Tìm theo tên hoặc email..."/><button onClick={()=>void load()} className="rounded-md border border-slate-200 px-3 text-xs font-semibold">Làm mới</button></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{['Nhân viên','Vai trò','Trạng thái','Ngày tạo','Thao tác'].map((x)=><th key={x} className={`px-5 py-3 ${x==='Thao tác'?'text-right':''}`}>{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={5} className="px-5 py-16 text-center text-slate-400">Đang tải dữ liệu…</td></tr>:filtered.length===0?<tr><td colSpan={5} className="px-5 py-16 text-center text-slate-400">Không có nhân sự phù hợp.</td></tr>:filtered.map((row)=><tr key={row.id} className="border-t border-slate-100"><td className="px-5 py-3"><b>{row.fullName||'Chưa cập nhật'}</b><p className="text-xs text-slate-400">{row.email}</p></td><td className="px-5 py-3 text-slate-600">{ROLE_LABEL[String(row.role||row.userType).toLowerCase()]||row.role}</td><td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${row.isBlocked?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'}`}>{row.isBlocked?'Đã khóa':'Hoạt động'}</span></td><td className="px-5 py-3 text-xs text-slate-400">{row.createdAt?new Date(row.createdAt).toLocaleDateString('vi-VN'):'—'}</td><td className="px-5 py-3 text-right"><button onClick={()=>openEdit(row)} className="mr-2 rounded border border-slate-200 px-2.5 py-1.5 text-xs">Sửa</button><button onClick={()=>void toggle(row)} className="mr-2 rounded border border-amber-200 px-2.5 py-1.5 text-xs text-amber-700">{row.isBlocked?'Mở khóa':'Khóa'}</button><button onClick={()=>void remove(row)} className="rounded border border-rose-200 px-2.5 py-1.5 text-xs text-rose-700">Xóa</button></td></tr>)}</tbody></table></div><footer className="border-t border-slate-100 px-5 py-3 text-xs text-slate-400">Hiển thị {filtered.length}/{rows.length} nhân sự</footer>
    </section>
    {modal&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/35 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-lg bg-white shadow-2xl"><header className="flex justify-between border-b px-5 py-4"><b>{modal==='create'?'Thêm nhân sự':'Cập nhật nhân sự'}</b><button type="button" onClick={()=>setModal(null)}>×</button></header><div className="space-y-3 p-5">{[['Họ và tên','fullName','text'],['Email','email','email'],['Mật khẩu','password','password']].map(([label,key,type])=><label key={key} className="block text-xs font-bold text-slate-600">{label}{key==='password'&&modal==='edit'?' (để trống nếu không đổi)':''}<input type={type} value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})} className="mt-1.5 w-full rounded-md border border-slate-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-emerald-600"/></label>)}<label className="block text-xs font-bold text-slate-600">Vai trò<select value={form.role} onChange={(e)=>setForm({...form,role:e.target.value})} className="mt-1.5 w-full rounded-md border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal">{ROLES.slice(1).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><footer className="flex justify-end gap-2 border-t px-5 py-4"><button type="button" onClick={()=>setModal(null)} className="rounded border px-4 py-2 text-sm">Hủy</button><button disabled={saving} className="rounded bg-emerald-700 px-4 py-2 text-sm font-bold text-white">{saving?'Đang lưu…':'Lưu'}</button></footer></form></div>}
  </>
}
